### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode saat install

### ISSUE THREAD

**Issue by irfanpule** [Midtrans/midtrans-python-client#4]
saya mengalami gagal install paket. versi python yang digunakan yaitu 3.6.4
```
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ny7wiyn3/midtransclient/setup.py", line 4, in <module>
        long_description = fh.read()
      File "/usr/share/nginx/html/projects/env/lib64/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 312: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-ny7wiyn3/midtransclient/
```

**Comment by irfanpule** [comment]
ini sudah bisa terpasang, tapi install paket saya unduh, lalu saya ubah `setup.py line 4` yang sebelumnya `long_description` nilai diambil dari membaca file Markdown saya ubah `long_description = ""` empty string

**Comment by rizdaprasetya** [comment]
Hi @irfanpule 
Hmm coba saya reproduce issuenya dengan python version latest dari `3.6` yaitu `3.6.8`, berhasil bisa install.

```
/home # git clone https://github.com/Midtrans/midtrans-python-client.git
Cloning into 'midtrans-python-client'...
remote: Enumerating objects: 46, done.
remote: Counting objects: 100% (46/46), done.
remote: Compressing objects: 100% (34/34), done.
remote: Total 167 (delta 19), reused 33 (delta 11), pack-reused 121
Receiving objects: 100% (167/167), 55.48 KiB | 573.00 KiB/s, done.
Resolving deltas: 100% (66/66), done.
/home # cd midtrans-python-client/
/home/midtrans-python-client # pip install .
Processing /home/midtrans-python-client
Requirement already satisfied: requests>=2.3.0 in /usr/local/lib/python3.6/site-packages (from midtransclient==1.0.7) (2.21.0)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/local/lib/python3.6/site-packages (from requests>=2.3.0->midtransclient==1.0.7) (1.24.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/site-packages (from requests>=2.3.0->midtransclient==1.0.7) (2019.3.9)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/site-packages (from requests>=2.3.0->midtransclient==1.0.7) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python3.6/site-packages (from requests>=2.3.0->midtransclient==1.0.7) (2.8)
Building wheels for collected packages: midtransclient
  Building wheel for midtransclient (setup.py) ... done
  Stored in directory: /root/.cache/pip/wheels/ae/6c/77/aa481f00022b26f56ec9e962e94063f0a7077b174172de9add
Successfully built midtransclient
Installing collected packages: midtransclient
Successfully installed midtransclient-1.0.7
/home/midtrans-python-client # python --version
Python 3.6.8
```

Environment Alpine Linux. Apakah Anda coba installnya pada env Windows? Bisa jadi encoding ASCII ada perbedaan antara UNIX & Windows based.
Atau mungkin downloadnya corrupted.

**Comment by rizdaprasetya** [comment]
Saya coba di Python `3.6.4` juga tetap bisa
```
/ # git clone git clone https://github.com/Midtrans/midtrans-python-client.git
/ # git clone https://github.com/Midtrans/midtrans-python-client.git
Cloning into 'midtrans-python-client'...
remote: Enumerating objects: 46, done.
remote: Counting objects: 100% (46/46), done.
remote: Compressing objects: 100% (34/34), done.
remote: Total 167 (delta 19), reused 33 (delta 11), pack-reused 121
Receiving objects: 100% (167/167), 55.48 KiB | 0 bytes/s, done.
Resolving deltas: 100% (66/66), done.
Checking connectivity... done.
/ # cd midtrans-python-client/
/midtrans-python-client # pip install .
Processing /midtrans-python-client
Collecting requests>=2.3.0 (from midtransclient==1.0.7)
  Downloading https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl (57kB)
    100% |████████████████████████████████| 61kB 3.4MB/s
Collecting urllib3<1.25,>=1.21.1 (from requests>=2.3.0->midtransclient==1.0.7)
  Downloading https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl (118kB)
    100% |████████████████████████████████| 122kB 3.3MB/s
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.3.0->midtransclient==1.0.7)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 4.5MB/s
Collecting certifi>=2017.4.17 (from requests>=2.3.0->midtransclient==1.0.7)
  Downloading https://files.pythonhosted.org/packages/60/75/f692a584e85b7eaba0e03827b3d51f45f571c2e793dd731e598828d380aa/certifi-2019.3.9-py2.py3-none-any.whl (158kB)
    100% |████████████████████████████████| 163kB 4.1MB/s
Collecting idna<2.9,>=2.5 (from requests>=2.3.0->midtransclient==1.0.7)
  Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 5.7MB/s
Building wheels for collected packages: midtransclient
  Running setup.py bdist_wheel for midtransclient ... done
  Stored in directory: /root/.cache/pip/wheels/4d/de/95/212a28e211547ace736efa9f40ec81b0442493d6503b160fd4
Successfully built midtransclient
Installing collected packages: urllib3, chardet, certifi, idna, requests, midtransclient
Successfully installed certifi-2019.3.9 chardet-3.0.4 idna-2.8 midtransclient-1.0.7 requests-2.21.0 urllib3-1.24.1
You are using pip version 9.0.3, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
/midtrans-python-client # python --version
Python 3.6.4
```

**Comment by rizdaprasetya** [comment]
Keliatannya pada line ini
https://github.com/Midtrans/midtrans-python-client/blob/ac8dfbc64243f46a337da58a6a94065e7b124d4b/setup.py#L3

Perlu ditambah explicit encoding param jadi
```
 with open("README.md", "r", encoding="utf-8") as fh: 
```
Tapi perlu dicek apakah ini akan work di all environment dan tidak introduce breaking changes

**Comment by irfanpule** [comment]
env berada apa UNIX based,  saya juga masih kurang ngerti di mesin satu lagi dengan versi `3.6.3` dan versi `3.6.7` di laptop saya berhasil install.
Terimakasih atas penjelasannya dan sarannya @rizdaprasetya
